# @package _global_
TRAIN:
  BATCH_SIZE: 32
  N_EPOCHS: 50
  SAVE_FREQ: 25
  LEARNING_RATE: 1e-4
  LR_MILESTONES: [50]
  GAMMA: .5
  BETAS: (.9, .999)
  WEIGHT_DECAY: 0
TEST:
  METRIC_NAME: 'ChamferDistance'
NETWORK:
  N_SAMPLING_POINTS: 2048
  GRIDDING_LOSS_SCALES: [128]
  GRIDDING_LOSS_ALPHAS: [0.1]
DIR:
  OUT_PATH: './output/grnet/'
CONST:
  WEIGHTS:
  DEVICE: '1'
  NUM_WORKERS: 8
  N_INPUT_POINTS: 2048
DATASETS:
  SHAPENET:
    CATEGORY_FILE_PATH: '/home/lxiaol9/3DGenNet2019/haoi-pose/config/datasets/ShapeNet.json'
    N_RENDERINGS: 8
    N_POINTS: 16384
    PARTIAL_POINTS_PATH: '/groups/arcadm/xiaolong/ShapeNetCompletion/%s/partial/%s/%s/%02d.pcd'
    COMPLETE_POINTS_PATH: '/groups/arcadm/xiaolong/ShapeNetCompletion/%s/complete/%s/%s.pcd'
DATASET:
  TRAIN_DATASET: 'ShapeNet'
  TEST_DATASET: 'ShapeNet'
