# @package _global_
DATASET:
  dataset_path: '/Users/halfsummer11/HalfSummer11/Research/projects/equivariant_pose/modelnet_data/'
  target_category: ''
  add_noise: False
  noise_trans: 0.04
  workers: 8
