# @package _global_
DATASET:
  batch_size: 2
  num_points: 512
  num_of_class: 10
  data_path: '/groups/CESCA-CV/ICML2021/data/modelnet40_normal_resampled/'
  target_category: ''
  num_gen_samples: 30
  workers: 8
