# @package _global_
DATASET:
  data_path: '/orion/u/yijiaw/projects/haoi/data/ycb'
  add_noise: False
  noise_trans: 0.04
  use_rgb: False
  num_classes: 21
  workers: 8
  so3_augment: False
instance:
