# @package _global_
defaults:
  - training: ae_gan # it may contain specific parameters
    optional: True
  - models: se3_transformer_default # for encoder setting only
    optional: True
  - datasets: obman
    optional: True

seed: 2913
mode: 'train'
no_cuda: False
device: ''

exp_num: '1'
exp_name: 'default'
task: 'pcloud_completion' # hand_regression, obj_reconstruction, hand_reconstruction, contacts_vote, pcloud_pose, pcloud_completion, partial_pcloud_pose
name_model: grnet         # Name of the specific model to load
encoder_type: 'se3_transformer'
decoder_type: 'fc'
template_shape: 'sphere'
use_wgan: False
is_debug: False

# datasets
name_dset: 'obman'
root_data: "/groups/CESCA-CV/ICML2021/data"
dataset_class: 'HandDataset'
item: 'obman'
target_category: ''
n_max_parts : 2
num_points: 512
nocs_type: 'A'
use_hand: False

# pred objective
pred_hand: True
pred_joint: False
pred_mano: False
pred_joint_ind: False
pred_nocs: False
pred_6d: False
pred_t: False
pred_bb: False
pred_seg: False
pred_conf: False
pred_mode: False
pred_center: False
rotation_use_dense: False
pred_sym_axis: False
use_hand_occupancy: False
check_consistency: True

# loss
num_modes_R: 1
rotation_loss_type: 1
use_1vN_nocs: False
use_objective_T: False
use_objective_R: False
use_objective_N: False
use_objective_C: False
use_objective_M: False
use_confidence_R: False
use_objective_V: False #
use_objective_P: False
use_objective_canon: False
confidence_loss_type: 0
confidence_loss_multiplier: 0.01
consistency_loss_multiplier: 0.1
modecls_loss_multiplier: 0.001
use_adaptive_mode: False
use_symmetry_loss: False
use_one2many: False
use_head_assemble: False
t_method_type: -1
r_method_type: -1
theta_max: 36.0
use_axis: False
use_fps_points: False

# data control
subset_samples: False
fetch_cache: False
use_preprocess: False
preprocess: False
augment: False
normalize: False
single_instance: False
verbose: False
is_gen: False
use_noisy_nocs: True
rot_align: False
sym_aligned_nocs: False
hand_only: False
use_partial: False
use_background: False
use_rgb: False
fixed_sampling: False

# eval
log_dir: '/model/${item}/${exp_num}'
use_pretrain: False
eval: False
eval_mini: False
pre_compute_delta: False
split: 'val'
pretrained_path: ''
is_testing: False
use_gt_M: False
eval_mode_r: 0
checkpoints_name: ''

# general, gpu, print
use_wandb: False
pretty_print: False
distributed: False
port: '8803'
num_gpus: 1
gpu: '0'
gpu_ids: 0
num_workers: 8
nframe: 1
f: aa

# visualization & eval
BS: 2
domain: 'unseen'
nocs: 'part'
hand: False
contact: False
vote: False
mano: False
save: False
save_fig: False
show_fig: False
viz: False
is_special: True
iteration: 0
words: 'c,se3,T' # 'c,se3,N'
