defaults:
  - training: pose # Task performed (segmentation, classification etc...)
    optional: True
  - model_type: pointnet2 # Type of model to use, e.g. pointnet2, rsconv etc...
    optional: True
  - dataset: shape2motion
    optional: True
  - models: '${defaults.1.model_type}.yaml'

exp_num: '1'
exp_name: 'default'
task: 'category_pose'
name_dset: 'shape2motion'
item: 'eyeglasses'
n_max_parts : 4
num_points: 2048
nocs_type: 'A'
num_expr: 0.01
name_model: pointnet2_charlesmsg # Name of the specific model to load
root_data: "/groups/CESCA-CV/ICML2021/data"
# log_dir: '/model/${item}/${name_model}_${exp_num}' #
log_dir: '/model/${item}/${exp_num}' #

# for
# control
verbose: False
use_pretrain: False
is_debug: False
is_gen: False
eval: False
pretrained_path: ''
is_testing: False
pred_hand: True
pred_joint: False
pred_mano: False
rot_align: False
pred_joint_ind: False
pretty_print: False
distributed: False
port: '8803'
num_gpus: 1
gpu: '0'
num_workers: 8
nframe: 1
f: aa

# visualizatio
show_fig: True
save_fig: False
