pretty_print: False
eval: False
exp_name: 'default'
exp_num: '0'
process_index: 1
process_num: 8
task: semantic_seg
model_name: kpconv # Name of the specific model to load
labels: './config/labels/semantic-kitti.yaml'
root_dataset: "/groups/CESCA-CV/dataset/"
log_dir: '/work/cascades/lxiaol9/4DSeg/log/point/${exp_name}/${model_name}_${exp_num}'
pretrained_path: '/work/cascades/lxiaol9/4DSeg/model/point/single_r4' 
# root_dataset: "/data2/datasets/tmp/kitti/dataset/"
# pretrained_path: '/homes/xili/log/semantic_seg_kpconv_1' 
# log_dir: '/homes/xili/log/${exp_name}/${task}_${model_name}_${exp_num}'
use_pretrain: False
dataset: 'SemanticKitti'
num_classes: 20
num_motion_calsses: 3
input_threads: 8
batch_num: 8
val_batch_num: 8
max_in_points: 20000
max_val_points: 20000
max_gpu_points: 30000
in_radius : 4.0
val_radius: 8.0
val_frame_skip: 1
display_interval: 20
n_frames  : 1
sample_range : 5
window_size  : 2
#########################
# Architecture definition
#########################
architecture: ['simple',
                'resnetb',
                'resnetb_strided',
                'resnetb',
                'resnetb',
                'resnetb_strided',
                'resnetb',
                'resnetb',
                'resnetb_strided',
                'resnetb',
                'resnetb',
                'resnetb_strided',
                'resnetb',
                'nearest_upsample',
                'unary',
                'nearest_upsample',
                'unary',
                'nearest_upsample',
                'unary',
                'nearest_upsample',
                'unary']

num_kernel_points: 15
first_subsampling_dl: 0.06
conv_radius: 2.5
deform_radius: 6.0
KP_extent: 1.2
KP_influence: 'linear' #('constant', 'linear', 'gaussian')
fixed_kernel_points: 'center'
aggregation_mode: 'sum'
first_features_dim: 128
in_features_dim: 5
# Dimension of input points
in_points_dim: 3

# Can the network learn modulations
modulated: False

# Batch normalization parameters
use_batch_norm: True
batch_norm_momentum: 0.02

deform_fitting_mode: 'point2point'
deform_fitting_power: 1.0              # Multiplier for the fitting/repulsive loss
deform_lr_factor: 0.1                  # Multiplier for learning rate applied to the deformations
repulse_extent: 1.2                    # Distance of repulsion for deformed kernel points

#####################
# Training parameters
#####################
GPU: ''
# Maximal number of epochs
max_epoch: 2000
learning_rate: 1e-2
momentum: 0.98
weight_decay: 1e-3
segloss_balance: 'none'
lr_decays: {i: 0.1 ** (1 / 150) for i in range(1, max_epoch)}
grad_clip_norm: 100.0
epoch_steps: 4000
checkpoint_gap: 5
validation_size: 200
class_w: []
# class_w: [6.0, 94.0]

# Augmentations
augment_scale_anisotropic: True
augment_symmetries: [True, False, False]
augment_rotation: 'vertical'
augment_scale_min: 0.8
augment_scale_max: 1.2
augment_noise: 0.001
augment_color: 0.8

saving: True
saving_path: ${log_dir}
